# Generated by Django 3.0.5 on 2022-01-24 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='fotoperfil/DoutorFotoPerfil/')),
                ('endereco', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('departamento', models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Pediatria', 'Pediatria'), ('Imunologistas', 'Imunologistas'), ('Anestesiologistas', 'Anestesiologistas'), ('Cirurgião', 'Cirurgião')], default='Cardiologista', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='fotoperfil/PacienteFotoPerfil/')),
                ('endereco', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20)),
                ('sintomas', models.CharField(max_length=100)),
                ('assinadoDoutorId', models.PositiveIntegerField(null=True)),
                ('admitirData', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteAltaDetalhes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacienteId', models.PositiveIntegerField(null=True)),
                ('pacienteNome', models.CharField(max_length=40)),
                ('assinadoDoutorNome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('sintomas', models.CharField(max_length=100, null=True)),
                ('admitirData', models.DateField()),
                ('saidaData', models.DateField()),
                ('diaPassado', models.PositiveIntegerField()),
                ('custoQuarto', models.PositiveIntegerField()),
                ('medicamentos', models.PositiveIntegerField()),
                ('taxaDoutor', models.PositiveIntegerField()),
                ('Outros', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Compromisso',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
        migrations.RenameField(
            model_name='compromisso',
            old_name='appointmentDate',
            new_name='compromissoData',
        ),
        migrations.RenameField(
            model_name='compromisso',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='compromisso',
            old_name='doctorId',
            new_name='doutorId',
        ),
        migrations.RenameField(
            model_name='compromisso',
            old_name='doctorName',
            new_name='doutorNome',
        ),
        migrations.RenameField(
            model_name='compromisso',
            old_name='patientId',
            new_name='pacienteId',
        ),
        migrations.RenameField(
            model_name='compromisso',
            old_name='patientName',
            new_name='pacienteNome',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
